---
- hosts: cdn-dashboard
  become: yes
  name: Install necessary package
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name:
          - git
    - name: Install lsof
      ansible.builtin.apt:
        name:
          - lsof
    - name: Install python venv setup
      ansible.builtin.apt:
        name:
          - python3-venv
    - name: Install python pip module
      ansible.builtin.apt:
        name:
          - python3-pip

    - name: Add openresty GPG key
      ansible.builtin.apt_key:
        url: https://openresty.org/package/pubkey.gpg
    - name: Add openresty repository
      ansible.builtin.apt_repository:
        repo: deb http://openresty.org/package/debian bullseye openresty
    - name: Install openresty package
      ansible.builtin.apt:
        name:
          - openresty
    
    - name: Add mongodb key
      ansible.builtin.apt_key:
        url: https://pgp.mongodb.com/server-6.0.asc
    - name: Add mongodb repository
      ansible.builtin.apt_repository:
        repo: deb http://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main
    - name: Install mongodb community edition
      ansible.builtin.apt:
        name:
          - mongodb-org
    
    - name: Install redis server
      ansible.builtin.apt:
        name:
          - redis-server