---
- hosts: cdn-dashboard
  become: yes
  name: Running process
  tasks:
    - name: Reload openresty proxy server
      ansible.builtin.command: 
        chdir: /opt/cdn_dashboard/
        cmd: openresty -c nginx.conf -p /opt/cdn_dashboard/ -s reload