---
- hosts: cdn-dashboard
  become: yes
  name: Running process
  tasks:

    - name: Find all process using port 80
      ansible.builtin.shell: "lsof -t -i:80"
      register: processes_on_port
      
    - name: Stop all processes running on port 80
      ansible.builtin.shell: "kill -9 {{ item }}"
      with_items: "{{ processes_on_port.stdout_lines }}"
      ignore_errors: yes

    - name: Find all process using port 8000
      ansible.builtin.shell: "lsof -i -i:8000"
      register: processes_on_port
      
    - name: Stop all processes running on port 8000
      ansible.builtin.shell: "kill -9 {{ item }}"
      with_items: "{{ processes_on_port.stdout_lines }}"
      ignore_errors: yes

    - name: Run openresty proxy server
      ansible.builtin.command: 
        chdir: /opt/cdn_dashboard/
        cmd: openresty -c nginx.conf -p /opt/cdn_dashboard/

    - name: Run Django application using Gunicorn
      community.general.gunicorn:
        app: "cdn_dashboard.wsgi"
        chdir: /opt/cdn_dashboard/
        venv: /opt/cdn_dashboard/venv
        
    - name: Running mongodb database
      ansible.builtin.systemd:
        name: mongod
        state: started
    
    - name: Start redis server
      ansible.builtin.command:
        chdir: /opt/cdn_dashboard/
        cmd: redis-server redis.conf
      