---
- hosts: cdn-dashboard
  become: yes
  name: Running process
  tasks:
    - name: Run openresty proxy server
      ansible.builtin.command: 
        chdir: /home/nguyenquangminh/cdn_dashboard/
        cmd: openresty -c nginx.conf -p /home/nguyenquangminh/cdn_dashboard/ -s reload
    - name: Running mongodb database
      ansible.builtin.systemd:
        name: mongod
        state: started
    
    - name: Start redis server
      ansible.builtin.command:
        chdir: /home/nguyenquangminh/cdn_dashboard/
        cmd: redis-server redis.conf
      