---
- hosts: cdn-dashboard
  become: yes
  name: Synchronize code
  tasks:
    - name: Pulling code from github
      ansible.builtin.git:
        repo: https://github.com/NguyenQuangMinh0504/cdn_dashboard
        dest: /opt/cdn_dashboard/
        update: yes
        clone: yes
        force: yes