---
- hosts: cdn-dashboard
  become: yes
  tasks:
    - name: Synchronize code
      ansible.posix.synchronize:
        src: /Users/nguyenquangminh/Desktop/PROJECT/solo-projects/cdn_dashboard/
        dest: /home/nguyenquangminh/cdn_dashboard/