---
- hosts: cdn-dashboard
  become: yes
  tasks:
    - name: Install RabbitMQ
      ansible.builtin.apt:
        name:
          - rabbitmq-server
      
    - name: Enable RabbitMQ service
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Add RabbitMQ user
      community.rabbitmq.rabbitmq_user:
        user: huststudent
        password: password
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        tags: "administrator"

    - name: Enable rabbitmq management plugin
      community.rabbitmq.rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
